spring:
  application:
    name: xetra
  datasource:
    url: jdbc:postgresql://localhost:5432/xetra
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  security:
    # ignored: /**
    user:
      name: username
      password: password
